version: '3'
services:
  social-manager:
    # Au lieu de 'build: .', on pointe vers l'image construite par GitHub
    image: ghcr.io/elmout33/social_manager:latest
    container_name: social-manager
    ports:
      - "8080:80"
    restart: always
    # Force le téléchargement de la nouvelle image à chaque (re)démarrage
    pull_policy: always